name: "release-and-publish"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    if: ${{ startsWith(github.event.head_commit.message, 'patch:') ||  startsWith(github.event.head_commit.message, 'minor:') || startsWith(github.event.head_commit.message, 'major:') }}
    runs-on: ubuntu-latest
    outputs:
      exit_code: ${{ steps.exit.outputs.code }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release-patch
        if: startsWith(github.event.head_commit.message, 'patch:')
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch

      - id: release-minor
        if: startsWith(github.event.head_commit.message, 'minor:')
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor

      - id: release-major
        if: startsWith(github.event.head_commit.message, 'major:')
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: major

  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: setup-node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - id: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
