name: "release-and-publish"

on:
  push:
    branches:
      - "master"

jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      bump: ${{ env.BUMP_VERSION_SCHEME }}
    steps:
      - id: patch
        if: startsWith(github.event.head_commit.message, 'patch:')
        env:
          BUMP_VERSION_SCHEME: patch
      - id: minor
        if: startsWith(github.event.head_commit.message, 'minor:')
        env:
          BUMP_VERSION_SCHEME: minor
      - id: major
        if: startsWith(github.event.head_commit.message, 'major:')
        env:
          BUMP_VERSION_SCHEME: major

  release:
    needs: semver
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: ${{ semver.outputs.bump_version_scheme }}

  publish:
    needs: release
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
